version: '3.4'

services:
  catapi:
    image: catapi
    build:
      context: .
    ports:
      - 8000:8000

  nginx:
    image: nginx:alpine
    depends_on:
      - catapi
    ports:
      - 80:80
      - 443:443
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './certs:/certs:ro'
