version: '3.4'

services:
  catapi:
    image: catapi
    build:
      context: .
    ports:
      - 8001:8001

  nginx:
    image: nginx:alpine
    depends_on:
      - catapi
    ports:
      - 444:444
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './certs:/certs:ro'
